version: '3'
services:
  demo-app:
      image: app-demo:v2
      ports:
        - 3000:3000
      volumes:
        - './src:/demo-docker/src'

  mongodb:
      image: mongo:5.0.6-focal
      ports:
        - 27017:27017
      volumes:
        - './data:/data/db'

